### ISSUE TITLE
Privacy aware batch identification

### ISSUE THREAD

**Issue by Roconda** [O2MC/dimml-mobile-sdk#79]
# Problem

Events are sent to the backend as a batch. While we can assume that a batch belongs to a single device, multiple batches can't be easily identified as belonging to a single device.

# Solution

Respecting the user's privacy is our main concern. Given that it's up to the implementing party the API should be able to support; no identifier, session identifier, persistent identifier(from high to low priority).

## No identifier (anonymous)

The user wants to go anonymous or hasn't given any consent yet. This should be the default setting since we must respect the user's privacy.

## Session identifier

A random identifier will be generated on each sdk instance generation.

## Persistent identifier

This will be the least privacy respecting option. Meaning there will be a persistent identifier stored on the device which is used to identify the user across sessions.

**Comment by EdwinVanRooij** [comment]
After a brief discussion with @Roconda, we've agreed upon the following.

# Solutions

The solutions above are a good start. These are the adjustments.

## No identifier (anonymous)
This remains the same. 

## Persistent identifier
We feel it is up to the app developer who uses our SDK to arrange a unique ID for their user's phones. If we'd do this as well, there's a huge chance that each user will have two ID's, which seems unnecessary. This could be their username, email, or anything else that they've collected with their user's consent. 

A setter on the O2MC class will be introduced to meet the desired behavior of a 'Persistent identifier'. It will look something like `o2mc.setIdentifier(...)`. In this setter, you'd enter the unique ID. 

# Session identifier
Additionally, you could choose to use a (temporary) session identifier. We'll generate a UUID for you, which you can then use to correlate various batches sent by the same device during a user session. This way, you don't need any user data, but you can still track generic user behavior.

**Comment by Roconda** [comment]
Briefly documented cfdf3c9
