### ISSUE TITLE
Optional json properties

### ISSUE THREAD

**Issue by Roconda** [O2MC/dimml-mobile-sdk#91]
# Problem
When sending json payload to the backend some properties might be optional(eg. event.properties and the deviceId while being anonymous, see cfdf3c9).

The backend team should be able to handle our optional json properties.

# Proposed solutions
The following pseudo payload will be used as an example.

```
{
    "foo": "bar"
}
```

## Set value to null
We could send the optional properties with a null value. This keeps the payload data consistent which could be useful when querying the data.

```
{
    "foo": null
}
```
## Not at all
We could leave them out entirely in case the property is not set. This saves a little amount of data sent over the wire.

```
{

}
```

**Comment by EdwinVanRooij** [comment]
For Android, the Gson library is used for serializing POJOs. Gson does not serialize fields that are null by default, so no overhead here either. Therefore, I'd also favor not sending optional fields at all.

**Comment by Roconda** [comment]
There is a strong consensus on not sending empty optional json properties at all.
